### ISSUE TITLE
Use unique_ptr + observers

### ISSUE THREAD

**Issue by fan1x** [preislet/Digit-recognition#6]
https://github.com/preislet/Digit-recognition/blob/b92787198729c0240c34d87a06a27c389f21760d/Neural_network/Neural_network/Neural_network.cpp#L193

Don't use shared_ptrs unless it's needed

**Comment by preislet** [comment]
Nakonec jsem to vyřešil tak, že jsem ve vektoru ActivationFunctions změnil shared ptry na unique, ale následně jsem vytvořil shared ptr na tento vektor. 

Toto řešení mi přišlo logické, jelikož mám pole unique ptrů na aktivační funkce a poté každému neuronu dám shared pointer na toto pole -> na jednotlivé třídy vede pouze unique_ptr, ale na vektor, kde jsou tyto unique ptry uloženy vede shared ptr.
